chore
netlify/netlify-lambda pull request #606
Opened 2022-08-01 13:42 UTC by danez

2023-02-14 00:02 UTC, klavavej requested changes
@danez Thanks for the review request! Nothing major but I left a few suggestions for smoothing out the flow and cleaning up the spelling and grammar so I'm requesting changes.

One thing I suggested in a couple places is removing the word "simply". This well-intentioned word can backfire and make people who find the directions confusing feel even worse about being confused. In general it's better to convey the simplicity of instructions by making the instructions themselves simple to follow rather than telling people explicitly that the process is simple.

2023-02-14 09:51 UTC, danez commented
Thanks for the detailed review. I applied all the changes.

2023-02-14 16:43 UTC, klavavej submitted a review, later dismissed
@danez - I see [one suggestion that wasn't committed](https://github.com/netlify/netlify-lambda/pull/606#discussion_r1105109640) (the suggestion to remove the pop culture reference from the README). I assume this was an accident since your last comment said you applied all the suggested changes, but please let me know if you skipped that one on purpose. 

I'm re-upping that suggestion to remove the pop culture reference but otherwise this looks good to me - thanks for applying my suggestions ✨

2023-02-14 16:43 UTC, klavavej commented on README.md
> +*So long, and thanks for all the fish!*
@danez - here's the one suggestion that wasn't committed. I'd still recommend removing this pop culture reference

2023-02-15 09:19 UTC, danez commented on README.md
> +*So long, and thanks for all the fish!*
Sorry I missed that.

2023-02-15 14:55 UTC, klavavej approved these changes
Thanks for that last change @danez !

2023-02-15 15:16 UTC, merged